### ISSUE TITLE
Support on DoH over Tor?

### ISSUE THREAD

**Issue by citypw** [stealth/harddns#1]
Hi @stealth , harddns is a very cool project. and I've been using it for a while. I have two questions: 

1) Any plan to suport DoH over Tor in the future?
2) I'm a little confused about the usage of standalone proxy mode. If dnsmasq/systemd-resolv is already use localhost:53, will it work w/ "harddnsd -l 127.0.0.1 -p 53" along w/ the current resolvers?

**Comment by citypw** [comment]
Forgot to mention that the research revealed that DoH over Tor is more resistant to the censorship:

https://arxiv.org/abs/1906.09682

**Comment by stealth** [comment]
Thx for the feedback. I didn't research yet what possibilities exist for DoH over tor.
Will most likely first add NS/MX types for the daemon.
If you have systemd-resolv running, you first need to kill it ofcorse, or use that trick:

harddnsd -l 127.0.0.2 and add 127.0.0.2 as first resolver

**Comment by citypw** [comment]
ah, I disabled systemd-resolv and it works now.  Looking forward to see more DNS records types landing into harddns. Thanks for great work!

**Comment by citypw** [comment]
I run harddnsd as a systemd service now. The config is here:
https://github.com/hardenedlinux/hardenedlinux_profiles/blob/master/linux-mint_desktop/harddns.service

Do you mind if I push it to harddns/config or you'll do it in somewhere else?

**Comment by stealth** [comment]
Ok, the thing is json DoH only supports A/AAAA by now so lil chance to have other types supported
shortly.
I will add the service file to contrib later
